# Generated by Django 5.2.7 on 2025-11-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0002_order_amount_order_payment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, default=None, help_text="Customer's UPI txn reference / UTR", max_length=100, null=True),
        ),
    ]
