# Generated by Django 5.2.7 on 2025-11-01 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billingapp', '0004_alter_order_payment_reference'),
    ]

    operations = [
    ]
